### ISSUE TITLE
[Feature] Develop a Figma design for the frontend

### ISSUE THREAD

**Issue by kailash360** [kailash360/Talk-Line#12]
## Is your feature request related to a problem? Please describe.

Currently the frontend does not have a dedicated design to work on. 

## Describe the solution you'd like

A Figma design (or any suitable reference) should be created that should help in developing the frontend of the application. The design link can be then embedded into the README.md and CONTRIBUTING.md for reference.

## Additional context

NA

**Comment by Shrey-Pokhriyal** [comment]
@kailash360 I would like to take this issue

**Comment by kailash360** [comment]
Sure @Shrey-Pokhriyal
