### ISSUE TITLE
[Feature] Add a common script for installing dependencies

### ISSUE THREAD

**Issue by kailash360** [kailash360/Talk-Line#14]
## Is your feature request related to a problem? Please describe.

Currently, the dependencies for frontend and backend need to be installed separately. 

## Describe the solution you'd like

It would be better if a common `package.json` file would exist in the root folder that would contain the script a common script command, say `install-all`, to install the deps of both frontend and backend. In future, this will allow to add scripts that are common to both frontend and backend.

## Additional context

NA

**Comment by Shrey-Pokhriyal** [comment]
@kailash360 I would like to work on this.

**Comment by kailash360** [comment]
Sure @Shrey-Pokhriyal

**Comment by kailash360** [comment]
Closed via #16
