### ISSUE TITLE
[Bug] Fix the README in root directory

### ISSUE THREAD

**Issue by kailash360** [kailash360/Talk-Line#15]
## Describe the bug

Currently, the [README.md](README.md) in root folder does not have proper details about installing the projects. It contains the information of installing only the backend locally.

## Expected behavior

The installation details should be present in a CONTRIBUTING.md file instead of the README.md which should actually redirect to the contributing guide.

## Additional context

NA

**Comment by Shrey-Pokhriyal** [comment]
@kailash360 the readme should just contain the brief of the project and the contributing,md should contain the proper installation guide ?

**Comment by kailash360** [comment]
Yes @Shrey-Pokhriyal , 
The README should also contain the tech stacks used in the project.

**Comment by Shrey-Pokhriyal** [comment]
@kailash360 could you please assign this to me?

**Comment by kailash360** [comment]
Sure @Shrey-Pokhriyal
