### ISSUE TITLE
[Modify] Configure environment variables in the frontend 

### ISSUE THREAD

**Issue by kailash360** [kailash360/Talk-Line#17]
## Is your modification request related to a problem? Please describe.

Currently, the frontend does not have any configuration for the environment variables

## Describe the modification you'd like

Environment variables should be added in the frontend using the `react-dotenv` package and they should be whitelisted in the `package.json` file. 
Currently we should have the environment variables for the following configs:
- Backend URL

## Additional context

NA

**Comment by Debajyoti111** [comment]
@kailash360 I would like to work on this!

**Comment by kailash360** [comment]
Sure @Debajyoti111
