### ISSUE TITLE
[Feature] Add basic routes and pages

### ISSUE THREAD

**Issue by kailash360** [kailash360/Talk-Line#22]
## Is your feature request related to a problem? Please describe.

Currently , the application does not have proper routes and pages. 

## Describe the solution you'd like

The routes and pages should be set up using `react-router-dom`

## Additional context

The nomenclature of the pages should be in accordance to the standard norms.

**Comment by cisnejo** [comment]
I'd love to do this, if you'd like to assign it. What pages do you want?

**Comment by kailash360** [comment]
Sure, go ahead @cisnejo

**Comment by kailash360** [comment]
currently, there should be the basic pages as in a social media application. You can surely expand it further if you want. However, it must include, a signup/login page, feed, profile and a page for a particular post, for now.

**Comment by cisnejo** [comment]
Alright, I'll work on that, thanks

**Comment by cisnejo** [comment]
### Issue:
I see that your figma file looks different than what's currently on the project. 

This is what it currently looks like:
![image](https://user-images.githubusercontent.com/96255825/194439666-206e63ac-735a-4aa6-8af5-a0de64d8ac50.png)

This is what figma looks like:
![image](https://user-images.githubusercontent.com/96255825/194439597-ffee674e-b292-4b16-a83a-7d3c6c92045f.png)

Do you have a preference for which one you want it to correspond to?

**Comment by kailash360** [comment]
The design is just for an idea of how the application will be looking like. It isn't necessary to follow the design exactly here.

**Comment by kailash360** [comment]
fixed by #24
