### ISSUE TITLE
[Feature] Add CORS configuration

### ISSUE THREAD

**Issue by kailash360** [kailash360/Talk-Line#25]
## Is your feature request related to a problem? Please describe.

Currently, the CORS configuration is not defined for the backend. This will result in CORS error once the backend is deployed.

## Describe the solution you'd like

A CORS configuration should be added.

## Additional context

NA

**Comment by Shrey-Pokhriyal** [comment]
@kailash360 i would like to take up this issue

**Comment by kailash360** [comment]
Go ahead @Shrey-Pokhriyal

**Comment by kailash360** [comment]
closed via #27
